### PR TITLE
Port from GObject to GLib

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Won't review yet.  TurtleArt is the primary source for this repository; changes should be made there first.

**Comment by quozl** [comment]
Please rebase on the branch associated with https://github.com/sugarlabs/activity-turtle-confusion/pull/7 and push there.

**Comment by chimosky** [comment]
what branch is that?

**Comment by quozl** [comment]
https://github.com/sugarlabs/activity-turtle-confusion/pull/8 contains these changes now.

**Comment by rhl-bthr** [comment]
Closing this, since #8 has the changes.

**Pull request closed without merging**
