### PR TITLE
Fix metadata | Add Screenshots

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Following missing parameters have been added or fixed in the activity metadata file `activity.info`
1. `url`
2. `repository`
3. `tags`
3. `summary` - Grammatical correction

Also, added some screenshots

I tested this activity through `licensecheck` for checking to have license compatibility. As advised, I built the .xo bundle through setup.py and the files inside contained many different licenses such as GPLv2, GPLv3, BSD, LGPL, and MIT. The repository follows MIT, hence considered compatible. Please advice on the issue as I couldn't find a definite place to check for license compatibility. And I am a little unsure.

Some places I did refer to. 
1. http://janelia-flyem.github.io/licenses.html
2. https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses
3. https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
4. https://github.com/librariesio/license-compatibility (Thinking of making a script from this, is it feasible)

If this looks good, I can follow the similar procedure with others. Thanks.

### CODE REVIEW

**Comment by quozl** [comment]
> added some screenshots

Are they recently acquired from a running instance of the activity?  They look a bit old.  Where did they come from?

> The repository follows MIT

What does that mean?  If you mean _license_ in `activity.info` is set to MIT, should it instead be set to multiple license scenario; each license separated by <kbd>;</kbd>?  Should the COPYING files for the other licenses be added?

Turtle Confusion is derived from Turtle Art, and has very little difference now.  Your work should be applicable to Turtle Art.

**Comment by vipulgupta2048** [comment]
> Are they recently acquired from a running instance of the activity? They look a bit old. Where did they come from?

No, I didn't. They are taken from the help-activity page (https://help.sugarlabs.org/en/_images/TurtleConfusion-40.png).

> What does that mean? If you mean license in activity.info is set to MIT, should it instead be set to multiple license scenario; each license separated by ;? Should the COPYING files for the other licenses be added?

I am not sure, but from what I have read. Since all licenses used are compatible to MIT, then we should be using only one COPYING to avoid confusion. I may be wrong. What do you think? I am yet to see multiple scenarios of licenses in an activity.info. The last I saw was here (http://wiki.laptop.org/go/Activity_bundles) which is old as we discussed.

`Repo follow MIT` meant that license mentioned in the license parameter of activity.info and the COPYING file that owner created.

**Comment by quozl** [comment]
Thanks for the reply.

> taken from the help-activity

Looking at the first screenshot.

It was copied from the Wiki by @rdrsadhu in https://github.com/godiard/help-activity/commit/79278e8f8d7ff768805bc5bf030f0a03963f5da9 about three months ago.

It was added to the Wiki in 2011, see [metadata](https://wiki.sugarlabs.org/go/File:TurtleConfusion.png).

In last few weeks, @yashagrawal3 ported the activity to GTK+ 3.  See https://github.com/sugarlabs/activity-turtle-confusion/pull/4.

What you propose is a misrepresentation.  The toolbars are substantially different.

So please;

* [ ] update the screenshots.

Also, as the screenshots are added to the bundle and make the bundle larger, please use the minimum number of screenshots needed to convey use of the activity, and optimise the png. 

Once you've made updated screenshots here, they can be contributed to Help Activity.

If you're unable to update screenshots because of your project scope, don't add old ones.

> yet to see multiple scenarios of licenses in an activity.info

Search for a <kbd>;</kbd> in the `license` key.  Cardsort, Clock, GMail, Jukebox and Memorize are examples.  Useful references:

* https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/bundle/__init__.py#L39
* https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines
* https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing

> the COPYING file that owner created.

Yes, it was C. Scott Ananian in 178e439d108850e5b561918813bf0e736b64eddd who added the `license` metadata, but several authors since have added files with different licenses.

**Comment by vipulgupta2048** [comment]
Thanks, I can surely try adding screenshots. Let me see what I can do.
Really interesting stuff @quozl, I never knew supplying open-source licenses could be such an intricate task. Good to learn new things.
- I searched through it, it seems we are in `Multiple Licensing Scenarios`, hence the other licenses should be added with by using `;` separator. Please state if I am right and wrong. 

`license = MIT; GPLv2; GPLv3; LGPL`

- One doubt I have is - I looked through the documentation for `licensecheck` and it just checks the first few lines (30) or so for the license. What happens if we have `Combined Dual License`, or you would know if someone is using it. Licensecheck might not be able to detect it (I tested it, doesn't)  
- Also, I was thinking of creating a SPDX license compatibility checker, I would like your advice on it.

**Comment by quozl** [comment]
> license = MIT; GPLv2; GPLv3; LGPL

Yes, that seems likely.  However, you must add `+` where the licenses say "or later", and there's no need for a space after the semicolon.

> Licensecheck might not be able to detect it 

Thanks.  I'm not surprised; tools like `licensecheck` are helpful, but not a complete solution.  There is no technological solution to this social problem.  `licensecheck` does have a `--lines=N` argument you might use.

> thinking of creating a SPDX license compatibility checker

Why?

**Comment by vipulgupta2048** [comment]
> Why?

Well, I was searching for something that could tell if licenses are compatible or not. Until I found some pretty good resources after hours of searching. https://github.com/librariesio/license-compatibility This does just that, but in Ruby.

**Comment by vipulgupta2048** [comment]
@quozl Some questions

- How to denote `BSD (2 clause) GENERATED FILE`upon searching I found that there are lots of types of BSD licenses. There is an example given on the Fedora website but I am not sure. 
- `LGPL (v2.1 or later) (with incorrect FSF address)` - What to do with the wrong address, I think that doesn't matter as no one procures licenses by mailing them on the address and it's not the 1980's :smile: 

There are LGPL (v2 or later) and this LGPL (v2.1 or later) and LGPL (v3 or later)
What to do? I can denote them like this if you find this correct. 
  
`LGPLv2+;LGPLv2.1+;LGPLv3+`

**Comment by quozl** [comment]
Ruby is said to be very good.  Why not use it?

You can correct address in license by downloading the latest version of the license from gnu.org.

Yes, you can denote them all.

**Comment by vipulgupta2048** [comment]
@quozl  I apologize for the delay. I have added new screenshots with reduced file sizes and also made corrections to the license mentions to fix the multiple license scenarios.

**Comment by quozl** [comment]
Thanks.  Reviewed to d29b1bf.  The screenshots look fine.  Now that we've got multiple license scenario, can you also add the COPYING files for each license?

**Comment by vipulgupta2048** [comment]
Sure thing, I need to add the same to multiple license scenario in other activities as well.

**Comment by vipulgupta2048** [comment]
@quozl I have not added BSD. Due to it being old and somewhere it's 2 Clause and somewhere it's 3 Clause. If this is fine, I will add the same changes to others as well.

**Comment by quozl** [comment]
Thanks.  Same will be needed at Turtle Art, as these two repositories are to be kept in step as much as possible until we can merge them.

**Comment by vipulgupta2048** [comment]
Sure, here's the PR referring to that https://github.com/sugarlabs/turtleart-activity/pull/61

**Pull request merged**
